type token =
  | IDENTIFIER of (string * Lexing.position)
  | GET of (Lexing.position)
  | SET of (Lexing.position)
  | BREAK of (Lexing.position)
  | DO of (Lexing.position)
  | INSTANCEOF of (Lexing.position)
  | TYPEOF of (Lexing.position)
  | CASE of (Lexing.position)
  | ELSE of (Lexing.position)
  | NEW of (Lexing.position)
  | VAR of (Lexing.position)
  | CATCH of (Lexing.position)
  | FINALLY of (Lexing.position)
  | RETURN of (Lexing.position)
  | VOID of (Lexing.position)
  | CONTINUE of (Lexing.position)
  | FOR of (Lexing.position)
  | SWITCH of (Lexing.position)
  | WHILE of (Lexing.position)
  | DEBUGGER of (Lexing.position)
  | FUNCTION of (Lexing.position)
  | THIS of (Lexing.position)
  | WITH of (Lexing.position)
  | DEFAULT of (Lexing.position)
  | IF of (Lexing.position)
  | THROW of (Lexing.position)
  | DELETE of (Lexing.position)
  | IN of (Lexing.position)
  | TRY of (Lexing.position)
  | CLASS of (Lexing.position)
  | ENUM of (Lexing.position)
  | EXTENDS of (Lexing.position)
  | SUPER of (Lexing.position)
  | CONST of (Lexing.position)
  | EXPORT of (Lexing.position)
  | IMPORT of (Lexing.position)
  | IMPLEMENTS of (Lexing.position)
  | LET of (Lexing.position)
  | PRIVATE of (Lexing.position)
  | PUBLIC of (Lexing.position)
  | INTERFACE of (Lexing.position)
  | PACKAGE of (Lexing.position)
  | PROTECTED of (Lexing.position)
  | STATIC of (Lexing.position)
  | YIELD of (Lexing.position)
  | LBRACE of (Lexing.position)
  | RBRACE of (Lexing.position)
  | LPAREN of (Lexing.position)
  | RPAREN of (Lexing.position)
  | LBRACK of (Lexing.position)
  | RBRACK of (Lexing.position)
  | DOT of (Lexing.position)
  | SEMI of (Lexing.position)
  | COMMA of (Lexing.position)
  | LT of (Lexing.position)
  | GT of (Lexing.position)
  | LE of (Lexing.position)
  | GE of (Lexing.position)
  | EQ2 of (Lexing.position)
  | NEQ of (Lexing.position)
  | EQ3 of (Lexing.position)
  | NEQ3 of (Lexing.position)
  | PLUS of (Lexing.position)
  | MINUS of (Lexing.position)
  | MULT of (Lexing.position)
  | DIV of (Lexing.position)
  | MOD of (Lexing.position)
  | PLUS2 of (Lexing.position)
  | MINUS2 of (Lexing.position)
  | LT2 of (Lexing.position)
  | GT2 of (Lexing.position)
  | GT3 of (Lexing.position)
  | AND of (Lexing.position)
  | OR of (Lexing.position)
  | XOR of (Lexing.position)
  | NOT of (Lexing.position)
  | NEG of (Lexing.position)
  | AND2 of (Lexing.position)
  | OR2 of (Lexing.position)
  | QUESTION of (Lexing.position)
  | COLON of (Lexing.position)
  | EQ of (Lexing.position)
  | PLUS_EQ of (Lexing.position)
  | MINUS_EQ of (Lexing.position)
  | MULT_EQ of (Lexing.position)
  | DIV_EQ of (Lexing.position)
  | MOD_EQ of (Lexing.position)
  | LT2_EQ of (Lexing.position)
  | GT2_EQ of (Lexing.position)
  | GT3_EQ of (Lexing.position)
  | AND_EQ of (Lexing.position)
  | OR_EQ of (Lexing.position)
  | XOR_EQ of (Lexing.position)
  | DOLLER of (Lexing.position)
  | BS of (Lexing.position)
  | NULL of (Lexing.position)
  | TRUE of (Lexing.position)
  | FALSE of (Lexing.position)
  | NUMERIC of ([`Dec of string | `Hex of string] * Lexing.position)
  | STRING of (string * Lexing.position)
  | EOF

val statement :
  (Lexing.lexbuf  -> token) -> Lexing.lexbuf -> Ast.stmt
val program :
  (Lexing.lexbuf  -> token) -> Lexing.lexbuf -> Ast.program
